name: Pylint

on: 
  push:
    paths-ignore:
      - 'foo/**'
       
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 black bandit
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C0114,C0115,C0116 --ignore=foo/bar.py *.py fixtures/*.py
    - name: Analysing the code with flake8
      run: |
        flake8 --exclude .git,.github,.idea,__pycache__,venv --max-line-length=85
    - name: Analysing the code with black
      run: |
        black --verbose --check --exclude .git,.github,.idea,__pycache__,venv .
    - name: Analysing the code with bandit
      run: |
        bandit -ll -r . -x .git,.github,.idea,__pycache__,venv
